name: Convert Surge to Clash

on:
  push:
    paths:
      - 'Surge/*.list'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Convert Surge to Clash
      run: |
        # Convert .list files in A folder to .yaml in B folder
        for file in Surge/*.list; do
          filename=$(basename "$file" .list)
          yaml_file="Test/RuleSet/${filename}.yaml"
          echo "payload:" > "$yaml_file"
          while IFS= read -r line; do
            if [[ $line == \#* ]]; then
              # Add indentation to comment lines
              echo "  $line" >> "$yaml_file"
            elif [[ $line == DOMAIN* ]]; then
              # Add lines starting with DOMAIN with the required format
              echo "  - $line" >> "$yaml_file"
            fi
          done < "$file"
        done

    - name: Sync folder 
      run: |
        # Delete .yaml files in CLash folder if corresponding .list file doesn't exist in Surge folder
        for file in CLash/RuleSet/*.yaml; do
          base_filename=$(basename "$file" .yaml)
          if [ ! -f "A/${base_filename}.list" ]; then
            rm "$file"
            echo "Deleted $file because corresponding .list file does not exist in Surge folder."
          fi
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add Test/RuleSet/*.yaml
        git commit -m "Automatically convert surge to clash"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
