name: Convert Surge to Clash

on:
  push:
    paths:
      - 'Surge/*.list'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Convert Surge to Clash
      run: |
        for file in Surge/*.list; do
          filename=$(basename "$file" .list)
          yaml_file="Test/RuleSet/${filename}.yaml"
          echo "payload:" > "$yaml_file"
          while IFS= read -r line; do
            if [[ $line == \#* ]]; then
              echo "$line" >> "$yaml_file"
            else
              echo "  - $line" >> "$yaml_file"
            fi
          done < "$file"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add Test/RuleSet/*.yaml
        git commit -m "Automatically convert surge to clash"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
